### ISSUE TITLE
Suggestion for starter code

### ISSUE THREAD

**Issue by MichelleArk** [alecjacobson/geometry-processing-parameterization#21]
In the starter code for vector_area_matrix.cpp, there is a line: 
`A.resize(F.maxCoeff()+1,F.maxCoeff()+1);`

Perhaps it should be changed to something like:
`
int V_size = F.maxCoeff()+1;
A.resize(V_size*2,V_size*2);
`
in order to stay consistent with the README.

**Comment by alecjacobson** [comment]
Good idea. If you post a pr for this, I'll merge it.
-Alec

**Comment by alecjacobson** [comment]
Made the change in a5abdd051eaa007ae4e0ea92de27c3df5cc2b4c5
