### ISSUE TITLE
Confused about a sign in L

### ISSUE THREAD

**Issue by dknyxh** [alecjacobson/geometry-processing-parameterization#27]
In the readme, `Mass-spring methods` section, `L_ij` is defined to have `w_ij` when `i!=j` and edge[i,j] exists. I am wondering why is this not `-w_ij` since expanding the equation `w_ij|u_i - u_j|^2` will gives us `w_ij u_i^2 + w_ij u_j^2 - 2w_ij  u_i u_j`.

**Comment by alecjacobson** [comment]
You're correct. It's a bit of a confusion of conventions. Often the Laplacian is assumed to have (mostly) non-negative off-diagonal entries. So this should be referring to `-L_ij`.
