### ISSUE TITLE
How to use this rep to generate uv-map of human 3d mesh?

### ISSUE THREAD

**Issue by ypflll** [alecjacobson/geometry-processing-parameterization#28]
Hi, Alec.
I am trying to generate uv-map of a human 3d mesh like:
![image](https://user-images.githubusercontent.com/12528364/45736789-90d94900-bc1e-11e8-9141-95f383adddf3.png)

The huamn body is triangled and has 7k vertices.
Can I use your rep to generate a uv map? how?

Thanks!

**Comment by alecjacobson** [comment]
This is a homework assignment for my course. It's a simplified version of the parameterization problem you describe. The main challenge for arbitrary meshes is finding good _cuts_ that will become the boundary of the UV flattening. Once you have those cuts determined you could use one of these methods to do the flattening, but even still there are more advanced, recent methods out there.

**Comment by ypflll** [comment]
Thanks for reply.
Actually I am using SMPL human 3d model from: http://smpl.is.tue.mpg.de/ .
It's really hard to parameterize it for me. However, I find that the model has an uv map itself(maybe manully annoted, not sure):

![image](https://user-images.githubusercontent.com/12528364/45757799-c8fc7e00-bc56-11e8-8390-56d2ae3088dd.png)

I'll try to use this, although I want a continous uv-map like this:
![image](https://user-images.githubusercontent.com/12528364/45757934-14af2780-bc57-11e8-8c9f-592de27712b6.png)

Maybe I can merge these parts in one?

**Comment by alecjacobson** [comment]
This looks like a nice parameterization. You could try to merge it into one. There's a paper called AutoCuts that can do similar things, but I bet you'd have to really hack at it to get it to use an existing UV map and just merge components.

**Comment by ypflll** [comment]
Thanks for your sharing! I'll try to use it.
