### ISSUE TITLE
Question in deriving equation

### ISSUE THREAD

**Issue by MaxwellFang** [alecjacobson/geometry-processing-parameterization#51]
![image](https://user-images.githubusercontent.com/20386582/56475150-77b5a680-6452-11e9-8914-f070f4fab91c.png)
I am not sure how to derive from the second line to the third line, the best derivation I got is sum_{i, j} ui ortho(uj - ui). Also, if the third line is correct since the two vectors multiplied are orthogonal to each other, which leads the result to 0.

**Comment by alecjacobson** [comment]
Thank you for pointing this out. The derivation had some typos. Please see the updated readme for a more explicit and cleaner version:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/2241689/56511085-b3577b80-64f9-11e9-9849-7c47fc9c8a2a.png">

**Comment by MaxwellFang** [comment]
Thank you for the explanation. Just one more question, why the last line contains an absolute value? Even in later discussion, U^T A U doesn't seem taken the absolute value either. Is that also a typo? Thank you

**Comment by alecjacobson** [comment]
It's not an absolute value it's the determinant.

**Comment by MaxwellFang** [comment]
Thanks for the explanation, I am going to close this issue
